const LANDING_PAGE_CARD_ONE_IMAGE_PATH = '/images/person_checking_list.svg';
const LANDING_PAGE_CARD_TWO_IMAGE_PATH = '/images/person_three_devices.svg';
const LANDING_PAGE_CARD_THREE_IMAGE_PATH = '/images/piggy_bank_savings.svg';
const LANDING_PAGE_CARD_ONE_TEXT = 'Track Your Lists';
const LANDING_PAGE_CARD_TWO_TEXT = 'From Any Device';
const LANDING_PAGE_CARD_THREE_TEXT = 'Know Your Budget';

const OURGROCERYLISTAPI_PRODUCTION = 'https://ourgrocerylist-backend.herokuapp.com';
const OURGROCERYLISTAPI_DEVELOPMENT = 'http://localhost:1337';

export default {
    LANDING_PAGE_CARD_ONE_IMAGE_PATH,
    LANDING_PAGE_CARD_TWO_IMAGE_PATH,
    LANDING_PAGE_CARD_THREE_IMAGE_PATH,
    LANDING_PAGE_CARD_ONE_TEXT,
    LANDING_PAGE_CARD_TWO_TEXT,
    LANDING_PAGE_CARD_THREE_TEXT,
    OURGROCERYLISTAPI_PRODUCTION,
    OURGROCERYLISTAPI_DEVELOPMENT
}